### PR TITLE
Import world spawns from TC

### PR DESCRIPTION
**Pull request by kelno**
Step1:
Better matching, as in https://github.com/ValorenWoW/sunstrider-core/pull/69 but with very close proximity matched as well (instead of exact coordinates)
[Step1 scripts](https://github.com/ValorenWoW/sunstrider-core/files/2663192/step1.zip)

Step2:
Import missing creatures/gameobjects from TC
To check them by hand!

Step3:
Import missing waypoints.

### CODE REVIEW

**Comment by ratkosrb** [comment]
Blizzard did changes to the old world in TBC, so I would go with the 3.3.5 spawns over the 1.12 ones. They added new quest hubs and creatures in zones that didn't have enough content. For example the pre-BC spawns in Blasted Lands differed a lot, you can watch the Joana leveling videos in that zone and you'll see that the spawns don't match what you see in TC.

**Comment by kelno** [comment]
Thanks for that input

**Comment by kelno** [comment]
My current import script for step2:
[creature.zip](https://github.com/ValorenWoW/sunstrider-core/files/2676022/creature.zip)

**Comment by kelno** [comment]
The gameobject part was removed and replaced with commit 5f7c0c6ba4182d99428a88c559a79b7724377124

**Pull request merged**
