### PR TITLE
Implement UndermapRecall [WIP]

### PR DESCRIPTION
**Pull request by Nolin7777**
**Changes proposed**:

- Safe recent player position until player has flag MOVEMENTFLAG_FALLING_FAR
- Port player back to position before MOVEMENTFLAG_FALLING_FAR is set
- Or repop on closest graveyard if the second point was not successful

**Tests performed**: (Does it build, tested in-game, etc)

- Tested in-game.

**Known issues and TODO list**:

- Find better conditions for UndermapRecall().

### CODE REVIEW

**Comment by kelno** [comment]
Nice! Two things:
- I believe the player could have gone just undermap and have the MOVEMENTFLAG_FALLING, but not MOVEMENTFLAG_FALLING_FAR. If I'm correct an incorrect safe position could be saved in that case.
- What about the legit falling far cases? Such as jumping in the void in Outland

**Comment by Nolin7777** [comment]
Point 1 Never happened while testing on my PTR.

Point 2 Good found, will do an exception for Outlands.

**Comment by kelno** [comment]
Okay I tried it on your ptr. It seems to work in most cases.
Several remarks:
- You can indeed save a wrong safe position if you send any movement packet after getting undermap. For example turning at any point when you're falling with save the current position. Thus checking for the movement flag `MOVEMENTFLAG_FALLING_FAR` is not a reliable to check if player is currently undermap, we need another way. I think an added condition of not saving a safe position when player has MOVEMENTFLAG_FALLING would do the trick.
- I see no good reason to have a special handling for gm's
- The Eye of the Storm BG also has legit falling far cases. I don't really like the solution to just exclude the maps that have possible legit case, most players will be running around in Outlands most of the time so this kind of defeat the purpose of this PR if it's not working in that continent.
- In this PR Battleground::HandlePlayerUnderMap is now dead code, it should be removed
- We should still use Map::GetMinHeight instead of checking the < -300.f height

**Comment by Nolin7777** [comment]
Gamemasters or god flagged players wouldn't die [here](https://github.com/ValorenWoW/sunstrider-core/pull/43/files#diff-88aeb9f93da8f7946309d53138a46d55R516), that's why I added a special case.

**Comment by kelno** [comment]
Okay about the gm part. Though I only see now that you teleport him on another map and RepopAtGraveyard immediately after it. Maybe this works on mangos but TrinityCore and sunstrider teleports to other maps are delayed at the next updates so this will cause problems. I think it's just simpler letting the gm die as everyone else.

I have an simple idea for the outlands case:
Checking if there is a map height at the player current location before choosing restoring it to the safe position. 
If there is a map somewhere above the player we'll know he wasn't supposed to fall there. 
Only problematic cases I can think of:
- If player jump in void but under a bridge, such as the one connecting Thousand Needles and Netherstorm, or the bridges in the Eye of the Storm. 
- If a player jumps in the void but under a flying rock

It is completely acceptable to me if these are the only wrong cases though. I may have an idea to fix the second one but would have to test it.

**Comment by woiwoz** [comment]
Usually, the emptiness only occurs when players use charge, blink, or fear. We can start with this.

**Pull request closed without merging**
